Category.create(name: 'General', handle: 'general')
Category.create(name: 'Science', handle: 'science')
Category.create(name: 'Education', handle: 'education')
Category.create(name: 'Gaming', handle: 'gaming')
Category.create(name: 'Sport', handle: 'sport')
